networks:
  ssvunidas:
    driver: bridge

services:
  backend:
    networks:
      - ssvunidas
    image: lucasleite946/unidas-backend:latest
    volumes:
       - public:/opt/backend/public
       - wwebjs_auth:/opt/backend/dist/.wwebjs_auth
       - wwebjs_cache:/opt/backend/dist/.wwebjs_cache
    ports:
      - "8010:8010"
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    networks:
      - ssvunidas
    image: lucasleite946/unidas-frontend:latest
    ports:
      - "3010:3010"
    environment:
      - CI=false
    env_file:
      - ./frontend/.env
    command: /bin/sh -c "serve -s build -l 3010"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker-environment-variables
  mysql:
    networks:
      - ssvunidas
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: Ssv159@@@
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ssvunidas
      MYSQL_USER: ssv
      MYSQL_PASSWORD: Ssv159@@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./basePadraoSSV.sql:/docker-entrypoint-initdb.d/basePadraoSSV.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  public:
  wwebjs_auth:
  wwebjs_cache:
  mysql_data: